### ISSUE TITLE
MVP roadmap

### ISSUE THREAD

**Issue by vitonsky** [vitonsky/deepink#1]
- [x] #2
- [x] #6
  - [x] Note creation
  - [x] Delete note
  - [x] Edit note
- [x] Implement basic features for note
  - [x] #9
  - [x] #8
- [x] #14
- [x] #17
- [x] #18 
- [x] #32
- [x] #33
- [x] Implement basic UX features
  - [x] #10
  - [x] Implement electron behavior to minimize to tray, instead of close window and close app only with context menu in tray icon
- [x] #66
- [ ] #67
- [x] #34
- [x] #117

# For next iterations

Security
- [x] Remove node specific code from frontend code
- [ ] Implement encryption for a single note and for a note groups
