### ISSUE TITLE
Improve UI behavior

### ISSUE THREAD

**Issue by vitonsky** [vitonsky/deepink#37]
- [ ] Focus on password input when workspace manager shown
- [ ] Sort tags by name
- [ ] Allow to manual sort tags by drag&drop
- [ ] #31

**Comment by vitonsky** [comment]
Too generic issue, so i temporary close it
