### ISSUE TITLE
Create issues from `TODO` comments

### ISSUE THREAD

**Issue by vitonsky** [vitonsky/deepink#63]
Automate creation issues from TODO comments.

- [ ] Issue must be created by merge PR
- [ ] Issue must have title with comment or its summarized version for too long comments
- [ ] Issue must have specific labels (triage, TODO)
- [ ] Issue must refer PR and line in commit with a TODO comment
- [ ] Issues must never be duplicated. But issue may contain references in comments, to a TODOs with the same texts

# Implementation

We may look for GitHub action that solve this problem, or we may implement it our self and publish then as another project
